import axios from 'axios'

export default {
    command: 'text2img',
    aliases: ['txt2img', 'ai-image', 'generate-image'],
    category: 'ai',
    description: 'Generate image from text using AI',
    usage: '<prompt>',
    cooldown: 10,
    
    async execute({ reply, args, sock, m }) {
        const text = args.join(' ')
        if (!text) throw 'Masukkan prompt untuk generate gambar!\n\nContoh: .text2img beautiful anime girl with blue hair'
          try {
            await reply('🎨 AI sedang membuat gambar...')
            
            // Menggunakan API Nekoyama text-to-image
            const response = await axios.get(`https://api.nekoyama.my.id/api/ai/text-to-image?prompt=${encodeURIComponent(text)}`)
            
            if (response.data?.status === 'success' && response.data?.data?.download_url) {
                const imageUrl = response.data.data.download_url
                const model = response.data.data.model || 'Janus-Pro-7B'
                
                // Download gambar dari URL
                const imageResponse = await axios.get(imageUrl, {
                    responseType: 'arraybuffer'
                })
                
                await sock.sendMessage(m.chat, {
                    image: Buffer.from(imageResponse.data),
                    caption: `🎨 *AI Generated Image*\n\n📝 *Prompt:* ${text}\n🤖 *Model:* ${model}\n⚡ Generated by Chisato AI`
                }, { quoted: m })
            } else {
                throw new Error('Gagal generate gambar')
            }        } catch (error) {
            console.error('Text2Image Error:', error)
            await reply('❌ Maaf, terjadi kesalahan saat generate gambar. Silakan coba lagi nanti.\n\n💡 *Tips:*\n- Gunakan deskripsi dalam bahasa Inggris\n- Buat prompt yang detail dan jelas\n- Hindari konten yang tidak pantas')
        }
    }
}
